# Form implementation generated from reading ui file 'newtagdialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewTagDialog(object):
    def setupUi(self, NewTagDialog):
        NewTagDialog.setObjectName("NewTagDialog")
        NewTagDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        NewTagDialog.resize(405, 303)
        self.formLayout = QtWidgets.QFormLayout(NewTagDialog)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=NewTagDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.nameEdit = QtWidgets.QLineEdit(parent=NewTagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameEdit.sizePolicy().hasHeightForWidth())
        self.nameEdit.setSizePolicy(sizePolicy)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushCheckBox = QtWidgets.QCheckBox(parent=NewTagDialog)
        self.pushCheckBox.setObjectName("pushCheckBox")
        self.horizontalLayout.addWidget(self.pushCheckBox)
        self.remoteComboBox = QtWidgets.QComboBox(parent=NewTagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remoteComboBox.sizePolicy().hasHeightForWidth())
        self.remoteComboBox.setSizePolicy(sizePolicy)
        self.remoteComboBox.setObjectName("remoteComboBox")
        self.horizontalLayout.addWidget(self.remoteComboBox)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewTagDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        self.forceCheckBox = QtWidgets.QCheckBox(parent=NewTagDialog)
        self.forceCheckBox.setObjectName("forceCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.forceCheckBox)
        self.label.setBuddy(self.nameEdit)

        self.retranslateUi(NewTagDialog)
        self.buttonBox.accepted.connect(NewTagDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewTagDialog.reject) # type: ignore
        self.pushCheckBox.toggled['bool'].connect(self.remoteComboBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewTagDialog)

    def retranslateUi(self, NewTagDialog):
        _translate = QtCore.QCoreApplication.translate
        NewTagDialog.setWindowTitle(_translate("NewTagDialog", "New tag"))
        self.label.setText(_translate("NewTagDialog", "&Name:"))
        self.nameEdit.setPlaceholderText(_translate("NewTagDialog", "Enter tag name"))
        self.pushCheckBox.setText(_translate("NewTagDialog", "&Push to:"))
        self.forceCheckBox.setText(_translate("NewTagDialog", "Replace an existing tag"))
