# Form implementation generated from reading ui file 'processdialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.localization import *
from gitfourchette.qt import *


class Ui_ProcessDialog(object):
    def setupUi(self, ProcessDialog):
        ProcessDialog.setObjectName("ProcessDialog")
        ProcessDialog.resize(400, 300)
        self.verticalLayout = QVBoxLayout(ProcessDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QLabel(parent=ProcessDialog)
        self.titleLabel.setText("TASK")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.statusLabel = QElidedLabel(parent=ProcessDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setText("PLEASE WAIT")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.commandLabel = QElidedLabel(parent=ProcessDialog)
        self.commandLabel.setEnabled(False)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel.sizePolicy().hasHeightForWidth())
        self.commandLabel.setSizePolicy(sizePolicy)
        self.commandLabel.setText("COMMAND")
        self.commandLabel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.commandLabel.setObjectName("commandLabel")
        self.verticalLayout.addWidget(self.commandLabel)
        self.progressBar = QProgressBar(parent=ProcessDialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QDialogButtonBox(parent=ProcessDialog)
        self.buttonBox.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Abort)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProcessDialog)
        self.buttonBox.accepted.connect(ProcessDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ProcessDialog.reject) # type: ignore
        QMetaObject.connectSlotsByName(ProcessDialog)

    def retranslateUi(self, ProcessDialog):
        pass
from gitfourchette.toolbox.qelidedlabel import QElidedLabel
